apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: contenedor01
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'contenedor' > index.html && python -m http.server 8081",
            ]
          resources:
            limits:
              memory: 500Mi
              cpu: 50m
            requests:
              memory: 500Mi
              cpu: 50m
